=== yuyu0419/test/employee.dtd
<!ELEMENT empWrap (tTitle,employee+)>
<!ELEMENT tTitle (empIdTit,userNameTit,pwTit)>
<!ELEMENT empIdTit (#PCDATA)>
<!ELEMENT userNameTit (#PCDATA)>
<!ELEMENT pwTit (#PCDATA)>
<!ELEMENT employee (empId, userName, pw)>
<!ATTLIST employee 
    empId ID #REQUIRED
>
<!ELEMENT empId (#PCDATA)>
<!ELEMENT userName (#PCDATA)>
<!ELEMENT pw (#PCDATA)>

=== yuyu0419/test/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empWrap SYSTEM "employee.dtd">
<?xml-stylesheet type="text/css" href="css/style.css"?>
<empWrap>
    <tTitle>
        <empIdTit>Code</empIdTit>
        <userNameTit>Product Name</userNameTit>
        <pwTit>Qty</pwTit>
    </tTitle>
    <employee empId="_101">
        <empId>101</empId>
        <userName>Jam21</userName>
        <pw>Axgp231@!</pw>
    </employee>
    <employee empId="_102">
        <empId>102</empId>
        <userName>Luc43</userName>
        <pw>Axgp231@!</pw>
    </employee>
    <employee empId="_103">
        <empId>103</empId>
        <userName>Jam22</userName>
        <pw>aXgp231@!</pw>
    </employee>
    <employee empId="_104">
        <empId>104</empId>
        <userName>Jam23</userName>
        <pw>Aaxgp231@!</pw>
    </employee>
    <employee empId="_105">
        <empId>105</empId>
        <userName>Luc44</userName>
        <pw>Axgp431@!</pw>
    </employee>
    <employee empId="_106">
        <empId>106</empId>
        <userName>Luc45</userName>
        <pw>AxGP7831@!</pw>
    </employee>
    <employee empId="_107">
        <empId>107</empId>
        <userName>Jam24</userName>
        <pw>Axgp231@!34</pw>
    </employee>
</empWrap>
